### PR TITLE
Report suggestions

### PR DESCRIPTION
**Pull request by kl0tl**
I’d like this plugin to report the improvements `hlint` suggests.

I can hide the suggestions behind a flag if you’d prefer not to show them by default.

### CODE REVIEW

**Comment by kaste** [comment]
Does this work already?

For regex changes: Please also post typical output from hlint in the issue.

**Comment by kl0tl** [comment]
Here’s an exemple of a message intercepted by this change: 

```
Suggestion: Avoid lambda using `infix`
Found:
  \ h -> runReaderT h env
Perhaps:
  (`runReaderT` env)
```

**Comment by kaste** [comment]
That's not the complete output, doesn't include line, col, filename. Any chance to capture the whole message, currently it only captures the first line? Looks like this would be very helpful at least for beginners.

Now, these 'suggestions' show up as 'error' in Sublime, correct? (E.g. in the error panel)

Maybe we should use the generic `error_type` group:

```
(?P<error_type>.+):\s
```

EDIT: Also please make Travis happy!

**Comment by kl0tl** [comment]
The plugin currently ignores the detailed messages for warnings and errors. Are you suggesting to capture it only for suggestions or also for warnings and errors? I tried to do it with

```py
'(?P<message>.+\nFound:\n.+\nPerhaps:\n.+)$'
```

and this works but the whole message then gets displayed on only one line in the phantom.

Regarding a generic `error_type` group I’m not sure what you mean. I tried to replace

```py
'(?:(?P<error>Error)|(?P<warning>Warning)|(?P<suggestion>Suggestion)):\s*'
```

with

```py
'(?:(?P<error>Error)|(?P<warning>Warning)|(?P<error_type>Suggestion)):\s*'
```

and

```py
'(?P<error_type>.+):\s'
```

but SublimeLinter doesn’t show anything for those patterns. Were you suggesting something else?

In the meantime I’ve edited the regex so HLint suggestions gets categorized as warnings and not as errors.

**Comment by kaste** [comment]
Unfortunately I don't have hlint installed so I cannot debug this. For the error_type, yes I really meant the catch all thing. If that doesn't work it's either a typo somewhere or a SublimeLinter bug.

The phantom one-liner... Can you show a screenshot? How does it look of you open the error panel. Command palette: show all errors 🤞

I can definitely pull this here though. Tell me if you want to look into it some more. Otherwise we ⛴️ it.

**Comment by kaste** [comment]
We switched to the JSON format. ✌️

**Pull request closed without merging**
